### ISSUE TITLE
Infura ID 

### ISSUE THREAD

**Issue by gelicamarie** [decentology/hyperverse-mono#37]
- currently all test apps is set to default and using one infura api key which can cause problems if we hit the limit
- need to test if we add a .env in our sample app and provide `INFURA_API_KEY` if it will switch it

**Comment by ngnathan** [comment]
It would also be good to have a way to accept other custom RPC URLs is possible (Alchemy, etc.)

**Comment by gelicamarie** [comment]
@jsheely this can be closed now right?
